### ISSUE TITLE
Self-defined instances

### ISSUE THREAD

**Issue by stymex** [w3bdev1/alter#2]
Will there be an option to add self-defined instances? Especially for the self-hosted addresses. 
Also a support for lingva would be nice.

**Comment by w3bdev1** [comment]
Hi, I'm already working on custom / self-defined instances. It will be available soon.

Earlier I was looking into libre translate. I'll look into lingva as well.

Thanks :)

**Comment by stymex** [comment]
Great, looking forward to it ;)

**Comment by w3bdev1** [comment]
Option to add self-defined instances has been added. You can try it out and give feedback :)   @stymex

**Comment by stymex** [comment]
@w3bdev1, just tested it, works great :) thanks!
