### ISSUE TITLE
Scrible doesn't load images when Alter is enabled

### ISSUE THREAD

**Issue by stymex** [w3bdev1/alter#3]
Alter seems to replace all of the medium cdn addresses with the instance domain, this leads images not being loaded properly.
When the medium article is reloaded on scribe with alter disabled, everything gets displayed without a problem
![Capture](https://user-images.githubusercontent.com/2510948/162613215-a519eea6-70d3-4575-9d7c-36d9155bde47.PNG)
![Capture2](https://user-images.githubusercontent.com/2510948/162613218-e294cac5-e33d-4eed-8d83-1c4d53e56ff3.PNG)
.

**Comment by w3bdev1** [comment]
Thanks for pointing out this bug.

Alter took a maximalist approach to redirect all links. It was a bad approach as some links remain broken since the instance provider may not host everything, for example, image in case of scribe.

It has been updated. I think it is working correctly :)
